version: 1.0.{build}

environment:
  matrix:
    - perl: "5.20.1.1"
    - perl: "5.24.1.1"

install:
  - cinst StrawberryPerl --version %perl% --allow-empty-checksums
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - mkdir %APPVEYOR_BUILD_FOLDER%\tmp
  - set TMPDIR=%APPVEYOR_BUILD_FOLDER%\tmp
  - perl -V

build_script:
  - perl Makefile.PL && dmake

test_script:
  - dmake test TEST_VERBOSE=1
