version: 1.0.{build}

environment:
  matrix:
    - perl: "5.14.4.1"
    - perl: "5.16.3.20170202"
    - perl: "5.18.4.1"
    - perl: "5.20.3.3"
    - perl: "5.22.3.1"
    - perl: "5.24.1.1"

platform:
  - x86
  - x64

install:
  - cinst StrawberryPerl --version %perl% --allow-empty-checksums
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - mkdir %APPVEYOR_BUILD_FOLDER%\tmp
  - set TMPDIR=%APPVEYOR_BUILD_FOLDER%\tmp
  - perl -V

build_script:
  - perl Makefile.PL
  - dmake OPTIMIZE="-W -Wall -O2 -g"

test_script:
  - dmake test TEST_VERBOSE=1
